language: csharp  
sudo: required  
dist: trusty
mono: none
dotnet: 2.0.3
before_script:
  - sudo apt install lsb lsb-core alien
  - cd ./cspTools
  - tar -xf linux-amd64_deb.tgz
  - sudo ./linux-amd64_deb/install.sh
  - sudo /opt/cprocsp/sbin/amd64/cpconfig -license -set "5050E-H3010-06DCZ-EGXF5-FFUXC"
  #install container
  - mkdir -p /var/opt/cprocsp/keys/travis/
  - cp -r ./G2001256.000 /var/opt/cprocsp/keys/travis/
  - cp -r ./G2012256.001 /var/opt/cprocsp/keys/travis/
  - cp -r ./G2012512.000 /var/opt/cprocsp/keys/travis/
  - /opt/cprocsp/bin/amd64/csptest  -absorb -certs -provtype 75 -provider "Crypto-Pro GOST R 34.10-2001 Cryptographic Service Provider" -pattern "G2001256.000"
  - /opt/cprocsp/bin/amd64/csptest  -absorb -certs -provtype 80 -pattern "G2012256"
  - /opt/cprocsp/bin/amd64/csptest  -absorb -certs -provtype 81 -pattern "G2012512"
  - /opt/cprocsp/bin/amd64/csptest  -keyset -enum_c -verifyc -uniq
  - /opt/cprocsp/bin/amd64/csptest  -keyset -enum_c -verifyc -fqcn
 # disable warnings
  - sudo sed -i '/[Parameters]/a warning_time_gen_2001=ll:9223372036854775807' /etc/opt/cprocsp/config64.ini
  - sudo sed -i '/[Parameters]/a warning_time_sign_2001=ll:9223372036854775807' /etc/opt/cprocsp/config64.ini
  - cd ..
  - ./clean.sh -all
script:    
  - ./build.sh
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Csp/tests/ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3411.Tests.Gost3411CryptoServiceProviderTests" /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Algorithms/tests/ /t:BuildAndTest  "/p:XunitOptions=-class System.Security.Cryptography.Hashing.Algorithms.Tests.Gost3411Tests"  /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Algorithms/tests/ /t:BuildAndTest  "/p:XunitOptions=-class System.Security.Cryptography.Hashing.Algorithms.Tests.Gost3411_2012_256Tests"  /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Algorithms/tests/ /t:BuildAndTest  "/p:XunitOptions=-class System.Security.Cryptography.Hashing.Algorithms.Tests.Gost3411_2012_512Tests"  /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Csp/tests/ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3410.Tests.Gost3410CryptoServiceProviderTests" /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Csp/tests/ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3410.Tests.Gost3410_2012_256CryptoServiceProviderTests" /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Csp/tests/ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Encryption.Gost3410.Tests.Gost3410_2012_512CryptoServiceProviderTests" /p:ForceRunTests=true
  - .dotnet/dotnet msbuild src/System.Security.Cryptography.Csp/tests/ /t:BuildAndTest "/p:XunitOptions=-class System.Security.Cryptography.Csp.Tests.Gost28147CryptoServiceProviderTest" /p:ForceRunTests=true
notifications:
  email:
    on_success: never # default: change
on_failure: never # default: always
